'use client';

import { useState } from 'react';
import type { CostComponent, CostEstimate, EvidenceStatus, FreightOption, Procurement, ProcurementState, Product } from '@/lib/types';

const money = (n: number) => `₦${Math.round(n).toLocaleString()}`;
const marketplaces = ['1688', 'Taobao', 'Pinduoduo', 'Alibaba'];
const categoryOptions = [
  { value: 'general_goods', label: 'General goods' },
  { value: 'electronics', label: 'Electronics' },
  { value: 'apparel', label: 'Apparel' },
];
const api = async <T,>(url: string, body: unknown) => { const res = await fetch(url, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(body) }); const json = await res.json(); if (!json.ok) throw new Error(json.error?.message ?? 'Request failed'); return json.data as T; };
const apiGet = async <T,>(url: string) => { const res = await fetch(url); const json = await res.json(); if (!json.ok) throw new Error(json.error?.message ?? 'Request failed'); return json.data as T; };
const nextProcurementActions: Partial<Record<ProcurementState, { state: ProcurementState; label: string; type: string }[]>> = {
  QUOTE_CREATED: [{ state: 'SUPPLIER_SELECTED', label: 'Mark supplier selected', type: 'SUPPLIER_SELECTED' }],
  SUPPLIER_SELECTED: [{ state: 'PROCUREMENT_STARTED', label: 'Start procurement', type: 'PROCUREMENT_STARTED' }],
  PROCUREMENT_STARTED: [{ state: 'WAREHOUSE_PENDING', label: 'Send to warehouse queue', type: 'WAREHOUSE_PENDING' }],
  WAREHOUSE_PENDING: [{ state: 'WAREHOUSE_RECEIVED', label: 'Mark warehouse received', type: 'WAREHOUSE_RECEIVED' }],
  WAREHOUSE_RECEIVED: [{ state: 'QC_PENDING', label: 'Start QC', type: 'QC_PENDING' }, { state: 'SHIPPING_PENDING', label: 'Skip QC and prepare shipping', type: 'SHIPPING_PENDING' }],
  QC_PENDING: [{ state: 'QC_PASSED', label: 'QC passed', type: 'QC_PASSED' }, { state: 'QC_FAILED', label: 'QC failed', type: 'QC_FAILED' }],
  QC_PASSED: [{ state: 'SHIPPING_PENDING', label: 'Prepare shipping', type: 'SHIPPING_PENDING' }],
  SHIPPING_PENDING: [{ state: 'SHIPPING_BOOKED', label: 'Mark shipping booked', type: 'SHIPPING_BOOKED' }],
  SHIPPING_BOOKED: [{ state: 'IN_TRANSIT', label: 'Mark in transit', type: 'IN_TRANSIT' }],
  IN_TRANSIT: [{ state: 'ARRIVED_NIGERIA', label: 'Mark arrived Nigeria', type: 'ARRIVED_NIGERIA' }],
  ARRIVED_NIGERIA: [{ state: 'DELIVERY_PENDING', label: 'Mark delivery pending', type: 'DELIVERY_PENDING' }, { state: 'COMPLETED', label: 'Complete pickup procurement', type: 'COMPLETED' }],
  DELIVERY_PENDING: [{ state: 'COMPLETED', label: 'Complete procurement', type: 'COMPLETED' }],
};

type EstimateForm = { quantity: number; destination: string; shippingPreference: string; deliveryPreference: string; weightKg: number; lengthCm: number; widthCm: number; heightCm: number; productCategory: string; declaredValue: string };

export default function Home() {
  const [url, setUrl] = useState('');
  const [product, setProduct] = useState<Product>();
  const [estimate, setEstimate] = useState<CostEstimate>();
  const [procurement, setProcurement] = useState<Procurement>();
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);
  const [recoveryId, setRecoveryId] = useState('');
  const [recoveryError, setRecoveryError] = useState('');
  const [form, setForm] = useState<EstimateForm>({ quantity: 10, destination: 'Lagos', shippingPreference: 'recommend', deliveryPreference: 'pickup', weightKg: 1, lengthCm: 30, widthCm: 20, heightCm: 15, productCategory: 'general_goods', declaredValue: '' });

  async function analyze() { setLoading(true); setError(''); setRecoveryError(''); setEstimate(undefined); setProcurement(undefined); try { setProduct(await api<Product>('/api/products/analyze', { url })); } catch (e) { setError(e instanceof Error ? e.message : 'Analysis failed'); } finally { setLoading(false); } }
  async function estimateCost() { if (!product) return; setLoading(true); setError(''); try { setEstimate(await api<CostEstimate>('/api/costs/estimate', { product, ...form, declaredValue: form.declaredValue ? Number(form.declaredValue) : undefined })); } catch (e) { setError(e instanceof Error ? e.message : 'Estimate failed'); } finally { setLoading(false); } }
  async function startProcurement() { if (!estimate) return; setLoading(true); setError(''); setRecoveryError(''); try { const created = await api<Procurement>('/api/procurement', { estimateId: estimate.id, selectedMode: estimate.recommendedMode }); setProcurement(created); setRecoveryId(created.id); } catch (e) { setError(e instanceof Error ? e.message : 'Procurement failed'); } finally { setLoading(false); } }
  async function recoverProcurement() { const id = recoveryId.trim(); if (!id) { setRecoveryError('Enter a procurement id to open an existing record.'); return; } setLoading(true); setError(''); setRecoveryError(''); try { const recovered = await apiGet<Procurement>(`/api/procurement/${encodeURIComponent(id)}`); setProduct(undefined); setEstimate(undefined); setProcurement(recovered); } catch (e) { setProcurement(undefined); setRecoveryError(e instanceof Error ? e.message : 'Procurement record not found. Check the id and try again.'); } finally { setLoading(false); } }
  async function recordProcurementEvent(newState: ProcurementState, type: string) { if (!procurement) return; setLoading(true); setError(''); try { setProcurement(await api<Procurement>(`/api/procurement/${procurement.id}/events`, { newState, type, data: { source: 'buyer_workspace', note: 'Recorded from MVP procurement timeline.' }, verified: false })); } catch (e) { setError(e instanceof Error ? e.message : 'Could not update procurement'); } finally { setLoading(false); } }

  return <main className="page">
    <HeroAnalyzer url={url} setUrl={setUrl} loading={loading} error={error} onAnalyze={analyze} />
    {product && <AnalysisSummary product={product} />}
    {product && <MissingInputsForm form={form} setForm={setForm} loading={loading} onEstimate={estimateCost} />}
    {estimate && <ImportDecision estimate={estimate} />}
    {estimate && <EvidenceLedger estimate={estimate} form={form} product={product} />}
    {estimate && !procurement && <ProcurementCheckpoint estimate={estimate} loading={loading} onStart={startProcurement} />}
    {procurement && <ProcurementRecord procurement={procurement} loading={loading} onAction={recordProcurementEvent} />}
    <ProcurementRecovery recoveryId={recoveryId} setRecoveryId={setRecoveryId} loading={loading} error={recoveryError} onRecover={recoverProcurement} />
    <footer className="footer">Software intelligence layer only. Not a freight company, warehouse, customs broker, sourcing agency, or payment company.</footer>
  </main>;
}

function HeroAnalyzer({ url, setUrl, loading, error, onAnalyze }: { url: string; setUrl: (v: string) => void; loading: boolean; error: string; onAnalyze: () => void }) {
  return <section className="hero"><nav className="nav"><div className="brand">Import Intelligence</div><div className="badge">Demo mode · reference rates only</div></nav><div className="heroGrid"><div><div className="eyebrow">China → Nigeria trade intelligence</div><h1>HOW MUCH WILL THIS REALLY COST IN NIGERIA?</h1><p className="sub">Paste a product link, see what can be verified, fill only the missing import details, then compare sea vs air before you buy.</p><div className="analyzeBox"><label className="label">Paste product URL</label><div className="urlRow"><input value={url} onChange={(e) => setUrl(e.target.value)} placeholder="1688 / Taobao / Pinduoduo / Alibaba URL" /><button onClick={onAnalyze} disabled={loading}>{loading ? 'Working…' : 'Analyze Product'}</button></div><div className="chips">{marketplaces.map((m) => <span className="chip" key={m}>{m}</span>)}</div>{error && <div className="warn">{error}</div>}</div><div className="trustList"><div className="trustItem"><span className="dot" />Marketplace data is not fabricated; unavailable product and supplier facts stay UNKNOWN.</div><div className="trustItem"><span className="dot" />Freight/customs are reference estimates; Rialo shows CONNECTED only when the verified devnet reachability integration is configured, otherwise mock fallback is used.</div></div></div><aside className="panel"><small>Decision flow</small><div className="metric">Sea vs Air</div><p>Analyze the link, provide missing shipment inputs, compare landed-cost ranges, then create an auditable procurement record only if the estimate is useful.</p></aside></div></section>;
}

function AnalysisSummary({ product }: { product: Product }) {
  const score = product.supplier?.score;
  return <section className="section"><SectionIntro step="02" title="What we could verify" copy="The product record separates marketplace facts from unavailable supplier data, so the estimate starts from honest evidence." /><div className="grid2"><div className="card"><div className="cardTop"><span className="pill">{product.marketplace}</span><EvidenceBadge status={product.extractionStatus} /></div><h2>{product.name}</h2><div className="facts"><Fact label="Price" value={product.priceLow ? `${product.currency} ${product.priceLow}` : 'Unavailable'} status={product.priceLow ? 'KNOWN' : 'UNKNOWN'} /><Fact label="MOQ" value={product.moq ?? 'Unavailable'} status={product.moq ? 'KNOWN' : 'UNKNOWN'} /><Fact label="Weight" value={product.weightKg ? `${product.weightKg}kg` : 'Needs input'} status={product.weightKg ? 'KNOWN' : 'UNKNOWN'} /><Fact label="Dimensions" value={product.dimensionsCm ? `${product.dimensionsCm.length}×${product.dimensionsCm.width}×${product.dimensionsCm.height}cm` : 'Needs input'} status={product.dimensionsCm ? 'KNOWN' : 'UNKNOWN'} /></div>{product.warnings.map((w) => <div className="warn" key={w}>{w}</div>)}</div><div className="card"><div className="cardTop"><span className="label">Supplier intelligence</span><EvidenceBadge status={product.supplier?.dataStatus ?? 'UNKNOWN'} /></div>{score?.score == null ? <><h2>Verified supplier score unavailable</h2><p className="muted">Live supplier extraction is unavailable in this MVP. Treat this supplier as unverified until the missing evidence is checked manually.</p></> : <><div className="risk">{score.score} / 100</div><p><b>Risk:</b> {score.riskLevel}</p><p className="muted">{score.explanation.join(' ')}</p></>} {!!score?.missingEvidence.length && <div><div className="label">Still needs verification</div><ul className="cleanList">{score.missingEvidence.map((m) => <li key={m}>{m}</li>)}</ul></div>}</div></div></section>;
}

function MissingInputsForm({ form, setForm, loading, onEstimate }: { form: EstimateForm; setForm: (f: EstimateForm) => void; loading: boolean; onEstimate: () => void }) {
  return <section className="section card"><SectionIntro step="03" title="What we still need from you" copy="These inputs are the minimum needed to estimate freight, clearing, customs placeholders, and local delivery allowances." /><div className="inputGroups"><InputGroup title="Shipment" helper="Needed to estimate sea CBM and air chargeable weight."><Field label="Quantity" type="number" value={form.quantity} onChange={(v) => setForm({ ...form, quantity: Number(v) })} /><Field label="Unit weight (kg)" type="number" value={form.weightKg} onChange={(v) => setForm({ ...form, weightKg: Number(v) })} /><Field label="Length cm" type="number" value={form.lengthCm} onChange={(v) => setForm({ ...form, lengthCm: Number(v) })} /><Field label="Width cm" type="number" value={form.widthCm} onChange={(v) => setForm({ ...form, widthCm: Number(v) })} /><Field label="Height cm" type="number" value={form.heightCm} onChange={(v) => setForm({ ...form, heightCm: Number(v) })} /></InputGroup><InputGroup title="Commercial" helper="Used for customs placeholder estimates. Confirm HS classification before relying on final duties."><Field label="Declared/product value (₦ optional)" value={form.declaredValue} onChange={(v) => setForm({ ...form, declaredValue: v })} /><Select label="Product category" value={form.productCategory} options={categoryOptions} onChange={(v) => setForm({ ...form, productCategory: v })} /></InputGroup><InputGroup title="Nigeria delivery" helper="Used for clearing and local delivery allowance."><Select label="Destination" value={form.destination} options={['Lagos', 'Abuja', 'Port Harcourt', 'Kano', 'Other']} onChange={(v) => setForm({ ...form, destination: v })} /><Select label="Delivery" value={form.deliveryPreference} options={[{ value: 'pickup', label: 'Pickup' }, { value: 'local_delivery', label: 'Local delivery' }]} onChange={(v) => setForm({ ...form, deliveryPreference: v })} /><Select label="Shipping preference" value={form.shippingPreference} options={[{ value: 'recommend', label: 'Recommend for me' }, { value: 'sea', label: 'Prefer sea' }, { value: 'air', label: 'Prefer air' }]} onChange={(v) => setForm({ ...form, shippingPreference: v })} /></InputGroup></div><button onClick={onEstimate} disabled={loading}>{loading ? 'Calculating…' : 'Calculate Sea vs Air'}</button></section>;
}

function ImportDecision({ estimate }: { estimate: CostEstimate }) {
  return <section className="section"><SectionIntro step="04" title="Sea vs Air import decision" copy="The recommendation uses the returned landed-cost ranges, transit windows, and your shipping preference." /><div className="decision"><div><div className="label" style={{ color: '#cbe4dc' }}>Recommended mode</div><div className="decisionMode">{estimate.recommendedMode}</div><div className="range">{money(estimate.totalLow)} – {money(estimate.totalHigh)}</div><p>{estimate.recommendation}</p></div><div className="decisionFacts"><Info label="Destination" value={estimate.destination} /><Info label="Confidence" value={estimate.confidence} /><Info label="Currency" value={estimate.currency} /></div></div><div className="grid2"><FreightCard option={estimate.sea} recommended={estimate.recommendedMode === 'SEA'} /><FreightCard option={estimate.air} recommended={estimate.recommendedMode === 'AIR'} /></div></section>;
}

function EvidenceLedger({ estimate, form, product }: { estimate: CostEstimate; form: EstimateForm; product?: Product }) {
  const selected = estimate.recommendedMode === 'SEA' ? estimate.sea : estimate.air;
  const byStatus = selected.components.reduce<Record<string, CostComponent[]>>((acc, c) => { (acc[c.status] ??= []).push(c); return acc; }, {});
  return <section className="section"><SectionIntro step="05" title="What is known and what is still uncertain" copy="Every major cost input is labeled so you can see what came from you, what was estimated, what needs a quote, and what is still unknown." /><div className="ledger"><LedgerGroup status="USER_PROVIDED" items={[`Quantity: ${estimate.quantity}`, `Destination: ${estimate.destination}`, `Unit weight: ${form.weightKg}kg`, `Dimensions: ${form.lengthCm}×${form.widthCm}×${form.heightCm}cm`, ...(form.declaredValue ? [`Declared value: ${money(Number(form.declaredValue))}`] : [])]} /><ComponentGroup status="ESTIMATED" components={byStatus.ESTIMATED ?? []} /><ComponentGroup status="REQUIRES_QUOTE" components={byStatus.REQUIRES_QUOTE ?? []} /><LedgerGroup status="UNKNOWN" items={[...(product?.extractionStatus === 'UNKNOWN' ? ['Marketplace live extraction unavailable'] : []), ...(product?.supplier?.score.missingEvidence ?? []).map((m) => `Supplier evidence missing: ${m}`)]} /></div><div className="card"><h3>Assumptions & warnings</h3>{estimate.assumptions.concat(estimate.warnings).map((a) => <div className="warn" key={a}>{a}</div>)}</div></section>;
}

function ProcurementCheckpoint({ estimate, loading, onStart }: { estimate: CostEstimate; loading: boolean; onStart: () => void }) {
  return <section className="section card checkpoint"><SectionIntro step="06" title="Create procurement record" copy="Create an auditable record only after reviewing the recommendation and unresolved uncertainty." /><div className="grid3 recordFacts"><Info label="Selected mode" value={estimate.recommendedMode} /><Info label="Estimated cost" value={`${money(estimate.totalLow)}–${money(estimate.totalHigh)}`} /><Info label="Destination" value={estimate.destination} /></div><div className="warn">This creates an auditable procurement record from this estimate. It does not book freight, make payment, activate escrow, operate a warehouse, or execute live Rialo transactions.</div><button onClick={onStart} disabled={loading}>{loading ? 'Creating…' : 'Create Procurement Record'}</button></section>;
}

function ProcurementRecovery({ recoveryId, setRecoveryId, loading, error, onRecover }: { recoveryId: string; setRecoveryId: (v: string) => void; loading: boolean; error: string; onRecover: () => void }) { return <section className="section card recover"><div><span className="label">Already have a procurement ID?</span><p className="muted">Reopen the auditable record without creating a duplicate procurement.</p>{error && <div className="warn">{error}</div>}</div><div className="urlRow"><input value={recoveryId} onChange={(e) => setRecoveryId(e.target.value)} placeholder="pr_..." /><button onClick={onRecover} disabled={loading}>{loading ? 'Opening…' : 'Open Record'}</button></div></section>; }
function ProcurementRecord({ procurement, loading, onAction }: { procurement: Procurement; loading: boolean; onAction: (state: ProcurementState, type: string) => void }) { return <section className="section card"><SectionIntro step="07" title="Procurement record / timeline" copy="A compact audit trail for this estimate-backed procurement record." /><span className="pill">Auditable procurement record</span><h2>{procurement.productName}</h2><div className="grid3 recordFacts"><Info label="Procurement ID" value={procurement.id} /><Info label="Mode" value={procurement.selectedMode} /><Info label="Cost range" value={`${money(procurement.totalLow)}–${money(procurement.totalHigh)}`} /><Info label="Destination" value={procurement.destination} /><Info label="Current state" value={procurement.state} /><Info label="Rialo" value={procurement.rialoStatus} /></div><div className="warn">This is an auditable procurement record only. Rialo CONNECTED means devnet RPC reachability only; it is not freight booking, payment/escrow, warehouse operation, or live procurement execution.</div><div className="actions">{(nextProcurementActions[procurement.state] ?? []).map((action) => <button key={action.state} onClick={() => onAction(action.state, action.type)} disabled={loading} className="secondary">{action.label}</button>)}</div><div className="timeline">{procurement.events.map((e) => <div className="event" key={e.id}>{e.previousState} → <b>{e.newState}</b><br /><span className="muted">{new Date(e.timestamp).toLocaleString()} · {e.type} · verified: {String(e.verified)}</span></div>)}</div></section>; }

function SectionIntro({ step, title, copy }: { step: string; title: string; copy: string }) { return <div className="sectionIntro"><span className="step">{step}</span><div><h2>{title}</h2><p className="muted">{copy}</p></div></div>; }
function EvidenceBadge({ status }: { status: EvidenceStatus }) { return <span className={`evidence evidence-${status.toLowerCase()}`}>{status.replace('_', ' ')}</span>; }
function Fact({ label, value, status }: { label: string; value: React.ReactNode; status: EvidenceStatus }) { return <div className="fact"><div><div className="label">{label}</div><div className="value">{value}</div></div><EvidenceBadge status={status} /></div>; }
function Info({ label, value }: { label: string; value: React.ReactNode }) { return <div><div className="label">{label}</div><div className="value">{value}</div></div>; }
function Field({ label, value, onChange, type = 'text' }: { label: string; value: string | number; type?: string; onChange: (v: string) => void }) { return <label><span className="label">{label}</span><input type={type} value={value} onChange={(e) => onChange(e.target.value)} /></label>; }
function Select({ label, value, options, onChange }: { label: string; value: string; options: Array<string | { value: string; label: string }>; onChange: (v: string) => void }) { return <label><span className="label">{label}</span><select value={value} onChange={(e) => onChange(e.target.value)}>{options.map((o) => typeof o === 'string' ? <option key={o} value={o}>{o.replace('_', ' ')}</option> : <option key={o.value} value={o.value}>{o.label}</option>)}</select></label>; }
function InputGroup({ title, helper, children }: { title: string; helper: string; children: React.ReactNode }) { return <div className="inputGroup"><h3>{title}</h3><p className="muted">{helper}</p><div className="inputGrid">{children}</div></div>; }
function FreightCard({ option, recommended }: { option: FreightOption; recommended: boolean }) { return <div className={`card freightCard ${recommended ? 'recommended' : ''}`}><div className="cardTop"><span className="pill">{option.mode}{recommended ? ' · Recommended' : ''}</span><EvidenceBadge status="ESTIMATED" /></div><div className="value">{money(option.totalLow)}–{money(option.totalHigh)}</div><div className="miniFacts"><span>Freight {money(option.freightOnlyLow)}–{money(option.freightOnlyHigh)}</span><span>{option.transitDaysLow}–{option.transitDaysHigh} days</span><span>{option.chargeable.value} {option.chargeable.unit} chargeable</span><span>{option.confidence} confidence</span></div>{option.warnings.map((w) => <div className="warn" key={w}>{w}</div>)}</div>; }
function LedgerGroup({ status, items }: { status: EvidenceStatus; items: string[] }) { if (!items.length) return null; return <div className="ledgerGroup"><EvidenceBadge status={status} /><ul className="cleanList">{items.map((item) => <li key={item}>{item}</li>)}</ul></div>; }
function ComponentGroup({ status, components }: { status: EvidenceStatus; components: CostComponent[] }) { if (!components.length) return null; return <div className="ledgerGroup"><EvidenceBadge status={status} />{components.map((c) => <div className="component" key={`${c.name}-${c.category}`}><div><b>{c.name}</b><div className="status">{c.confidence} · {c.source}</div>{c.assumptions.map((a) => <div className="muted" key={a}>{a}</div>)}</div><div>{money(c.amountLow)}–{money(c.amountHigh)}</div></div>)}</div>; }
